name: Nix build + push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - name: Cachix build
      uses: cachix/cachix-action@v5
      with:
        # Name of a cachix cache to push and pull/substitute
        name: goffrie
        # Signing key secret retrieved after creating binary cache on https://cachix.org
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Nix file to build. Defaults to default.nix
        file: build.nix
    - name: Get deployment SSH key
      uses: shimataro/ssh-key-action@v2.0.1
      with:
        # SSH private key
        key: ${{ secrets.DEPLOY_REPO_SSH_KEY }}
        # public keys of SSH servers
        known_hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        # SSH key file name (default: id_rsa)
        name: id_rsa # optional, default is id_rsa
    - name: Push to deployment repo
      run: git fetch --unshallow origin &&
           git remote add deploy git@github.com:goffrie/strawberry-deploy.git &&
           git fetch deploy master &&
           if [[ $(git merge-base deploy/master HEAD) != $(git rev-parse HEAD) ]]; then git push --force-with-lease deploy HEAD:master; fi
